const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.GamePush_Channels,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.Sprite,
		C3.Plugins.HTMLElement,
		C3.Plugins.iframe,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Button,
		C3.Plugins.progressbar,
		C3.Plugins.List,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.System.Exps.layerscrolly,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Cnds.PickByUID,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Plugins.progressbar.Acts.SetCSSStyle,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Eponesh_GameScore.Exps.VariablesGet,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.progressbar.Acts.SetMaximum,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Button.Acts.SetCSSStyle,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Cnds.VariablesHas,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.HTMLElement.Acts.SetContent,
		C3.Plugins.HTMLElement.Acts.SetCSSStyle
	];
};
self.C3_JsPropNameTable = [
	{GeoChannels: 0},
	{GeoUser: 0},
	{DesktopScreenshot2: 0},
	{fileselement: 0},
	{iframe: 0},
	{fileico: 0},
	{Fon1: 0},
	{Text: 0},
	{SettingIco: 0},
	{HelpIco: 0},
	{KrugIco: 0},
	{Mouse: 0},
	{Текст: 0},
	{Fon3: 0},
	{Fon2: 0},
	{Button: 0},
	{DiskInfoIndikator: 0},
	{gbZanato_txt: 0},
	{maxGB_txt: 0},
	{netFile_txt: 0},
	{HTMLЭлемент: 0},
	{Список: 0},
	{Спрайт: 0},
	{Picsart_260215_: 0},
	{Logo: 0},
	{maxGB: 0},
	{zapGB: 0}
];

self.InstanceType = {
	GeoChannels: class extends self.C3.Plugins.GamePush_Channels.Instance {},
	GeoUser: class extends self.C3.Plugins.Eponesh_GameScore.Instance {},
	DesktopScreenshot2: class extends self.ISpriteInstance {},
	fileselement: class extends self.IHTMLElementInstance {},
	iframe: class extends self.IIframeInstance {},
	fileico: class extends self.ISpriteInstance {},
	Fon1: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	SettingIco: class extends self.ISpriteInstance {},
	HelpIco: class extends self.ISpriteInstance {},
	KrugIco: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Текст: class extends self.ITextInstance {},
	Fon3: class extends self.ITiledBackgroundInstance {},
	Fon2: class extends self.ISpriteInstance {},
	Button: class extends self.IButtonInstance {},
	DiskInfoIndikator: class extends self.IProgressBarInstance {},
	gbZanato_txt: class extends self.ITextInstance {},
	maxGB_txt: class extends self.ITextInstance {},
	netFile_txt: class extends self.ITextInstance {},
	HTMLЭлемент: class extends self.IHTMLElementInstance {},
	Список: class extends self.IListInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Picsart_260215_: class extends self.ISpriteInstance {},
	Logo: class extends self.ISpriteInstance {}
}